first step
TorchRik/NeuralNetwork pull request #1
Opened 2023-05-05 03:50 UTC by TorchRik

2023-05-15 21:26 UTC, DimaTrushin requested changes
1) Нравится, что по сути pure функции.
2) Плохо передаешь аргументы функциям. Векторы передаешь по значению или по неконстантной ссылке, даже когда их не надо менять. Это все надо поправить.
3) Часто делаешь лишнии копии тяжелых объектов вместо мува данных.
4) Я бы еще добавил стирающие типы для разных лоссов и разных функций активации.
5) Замени enum на enum class.

Потом еще гляну.

2023-05-15 21:26 UTC, DimaTrushin commented on CMakeLists.txt
> +
set(CXX_STANDARD_REQUIRED ON)

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.cpp
> +#include "neural_network.h"
кирпичи

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +    assert(!dimensions.empty());
Почему имплементация не вынесена в cpp файл? Особенно, что он есть и пустой?

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +      }
Плохо, что if не под assert-ом, он будет выстреливать и в релизе (гипотетически). Лучше записать условие в виде импликации: assert( index != nullptr ==>> "условие проверки");

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +                std::vector<ActivationFunctionType> activationFunctionsTypes,
Плохо делать зависимость от конкретного контейнера std::vector. Лучше делать std::initializer_list.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +  NeuralNetwork(std::vector<LayerDimension>& dimensions,
Почему ты перехватываешь данные по ссылке? Это очень странно и не нужно для конструктора. Во-первых, ты не можешь сюда скормить временный объект, то есть сделать что-то вроде
```cpp
NeuralNerwork Net{{dim1, dim2}, ...};
```
Во-вторых, задача этих аргкментов в том, чтобы построить объект, они либо перемещаются внутрь объекта, либо по ним строится что-то еще. Менять их нет никакого смысла.
Потому аргументы конструктора, это либо: const T&, либо T&&, либо T.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +      lastDimension = dimensions[index];
Зачем тебе lastDimension. Это загромождает код.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +    size_t layers_size = dimensions.size();
Зачем эта переменная?

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +        assert(lastDimension.n == dimensions[index].m);
Тут можно делать проверку размеров без lastDimension.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +          Layer(dimensions[index], activationFunctionsTypes[index]));
Если хочешь делать emplace_back, то надо передавать аргументы конструктору сразу. Например, 
```cpp
 layers_.emplace_back(dimensions[index], activationFunctionsTypes[index]);
```
Иначе это от push_back ничем не отличается.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +  NeuralNetwork(const std::string& pathToFile) {
Нейронка не должна уметь читать себя из файла. Этим должен заниматься какой-нибудь парсер, который вызывается в конструкторе. Потому что это не задача нейронки работать с какими-то внешними потоками или другими хранилищами.
Обычно это решается перегрузкой операторов сериализации и десериализации вроде operator<< и operator>> и наличием дефолтного конструктора, создающим "пустую" нейронную сеть. Для этого все компоненты нейросети должны уметь себя сериализовать и десериализовать. Ты же тут занимаешься десериализацией компонентов. Это нарушение уровня абстракции. То есть я бы видел код так
```cpp
std::istream& operator>>(std::istream& in, NeuralNetwork& net) {
  in >> layers_;
  in >> lossFunction_;
  return in;
}
```

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +  LossFunctionPtr lossFunction_;
Какого хрена тут ptr, а не переменная?
UPD Увидел, что ты без стирающих типов. Печаль.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +  using LossFunctionPtr = std::unique_ptr<LossFunctions::BaseLossFunction>;
Вместо этой фигни нужно использовать стирающий тип. Но на первых парах такое решение сойдет.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +      computedX = layer.compute(computedX);
тут можно сделать std::move(computedX) и принимать Vector&& на вход или Vector, чтобы не было лишних копирований.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +  [[nodiscard]] std::vector<Vector> computeEachLayer(const Vector& x) const {
Зачем эта функция? Ты хочешь кэшировать промежуточные вычисления?

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +    std::vector<Vector> computedLayers;
Сделай reserve ты же знаешь сколько у тебя векторов.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +    computedLayers.emplace_back(computed);
тут нет разницы между push_back и emplace_back

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +
В функции куча лишних копирований. Думаю можно избавиться так
```cpp
ComputedLayers.push_back(x);
for (const auto& layer : layers_)
  ComputedLayers.push_back(layer.compute(ComputedLayers.back()));
```

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +      }
Костыли вокруг unsigned типов. Но любопытно, я не думал, что так можно исправлять.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +                             std::vector<LayerDelta>& layersDeltas) {
Есть такая парадигма, что аргументы делят на входящие in и исходящие out. Входящие передают по константной ссылке или по значению const T& или T. А исходящие передают по указателю. Все входящие ставят в начале, а исходящие в конце. Тогда видно какие аргументы ты меняешь, а какие нет. Сравни
```cpp
int x = 5;
f(x);
// или
int x = 5;
f(&x);
```
Вторая ситуация подсказывает, что x изменится внутри f со стороны вызывающего функцию. А в первой надо лезть и проверять, что там в функции происходит. Например scanf по этому принципу действует и многие другие сишные функции.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +  void trainByBatch(std::vector<Vector> batchX, std::vector<Vector> batchY,
Плохая тема передавать векторы by value. Только если ты их не муваешь кудато. Почему не по константной ссылке? Если так, то почему это не приватный метод?

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +  void addOnIterationsDeltas(const Vector& x, const Vector& y,
Я не смог понять по названию, что делает метод.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +  void trainByBatch(std::vector<Vector> batchX, std::vector<Vector> batchY,
Это обучиться один раз на батче?

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +          LayerDelta{Matrix::Zero(layerDimension.n, layerDimension.m),
LayerDelta -- это что, название класса?

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +                    std::vector<size_t>& indexes) {
А почему этот передается по ссылке? Он где-то меняется?

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +  double getAverageLoss(std::vector<Vector>& X, std::vector<Vector>& Y) const {
почему не константные ссылки?

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +          lossFunction_->computeLoss(predict(X[index]), Y[index]) / X.size();
А почему не делишь на X.size() в самом конце единожды? Это с точностью как-то связано?

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +  void train(size_t iterationCount, size_t batchSize, std::vector<Vector>& X,
Еще надо указывать точность до которой ты хочешь обучить, чтобы ты либо учился до нужной точности, либо по истечению количества итераций (эпох).

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +      }
Нарушение уровня абстракции, ты тут просто генерируешь лист индексов, тут должно быть
```cpp
Random rnd = Random::Uniform(0, X.size() - 1);
for ( size_t i = 0; i < iterationCount; ++i) {
  std::vector<size_t> indices = random_permutation(rnd);
  ...
}
```
и вся работа по генерации лежит на этой функции. Более того, всю работу с рандомом по сути надо зашивать в отдельный класс.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +    std::uniform_int_distribution<> dist(0, X.size() - 1);
Вот тут по сути идет инициализация рандома. Это хорошо бы зашить в одну строчку в инициализацию отдельного класса. Например 
```cpp
Random rnd = Random::Uniform(0, X.size() - 1);
```

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +      std::cout << "Iteration " << ++currentIterationNum
Я бы не просто выводил точность, а останавливался, когда нужная точность достигнута.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +      }
Не уверен, что до конца понимаю, как это все работает.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +  void saveDataToFile(const std::string& pathToFile) const {
Это сериализация. У тебя класс должен делигировать сериализацию только своим членам, а они сами должны уметь сериализоваться.

2023-05-15 21:26 UTC, DimaTrushin commented on src/activations_functions.h
> +enum ActivationFunctionType { RELU, SIGMOID, SOFTMAX};
- Сделай enum class чтобы имена не утекали в global namespace.
- Не делай названия только большими буквами, так обозначают только макросы.

2023-05-15 21:26 UTC, DimaTrushin commented on src/activations_functions.h
> +std::unique_ptr<BaseActivationFunction> getActivationFunctionByType(
1) inline иначе у тебя ODR violation.
2) А вот были бы стирающие типы...

2023-05-15 21:26 UTC, DimaTrushin commented on src/activations_functions.h
> +  }
Нужен дефолтный case

2023-05-15 21:26 UTC, DimaTrushin commented on src/layer.h
> +using Vector = Eigen::VectorXd;
Ты в каждом файле эти using-ги делаешь заново. Мне кажется было бы лучше их подтягивать друг за другом. Чтобы не было конфликта. Либо уж тогда делать using-ги только внутри класса. В чем принципиальная разница. namespace можно открыть где угодно и добавить в него что угодно, а класс всегда лежит только в одном файле. Потому у тебя меньше шанса сделать конфликтующие using-ги внутри класса, но очень легко сделать такую проблему в namespace.

2023-05-15 21:26 UTC, DimaTrushin commented on src/layer.h
> +  ssize_t m;
Если ты используешь знаковые числа для размерностей, то используй знаковые числа везде. Но надо поставить assert-ы на положительность.

2023-05-15 21:26 UTC, DimaTrushin commented on src/layer.h
> +  const LayerDelta& operator+=(const LayerDelta&& other) {
Бессмысленная сигнатура const LayerDelta&&
Надо либо const LayerDelta&, либо LayerDelta&&
Твое определение равносильно по сути первому.
Так же супер мега глупо возвращать const LayerDelta&, должно быть LayerDelta&.

2023-05-15 21:26 UTC, DimaTrushin commented on src/layer.h
> +    layerDelta.deltaB /= num;
Если у тебя есть inplace операции, то другие операции надо определять через них, должно быть
```cpp
auto result = *this;
result /= num;
return result;
```

2023-05-15 21:26 UTC, DimaTrushin commented on src/layer.h
> +    b_ = Vector::Random(dimension.n);
1) Eigen по умолчанию инициализирует равномерным распределением. А лучше инициализировать нормальным распределением. Вот тут есть продвинутые методы инициализации для Eigen
https://bab2min.github.io/eigenrand/v0.5.0/en/index.html
Там есть ссылка на github, потому можно подключить как git submodule.
2) Ну почему никто из вас не пользуется списками инициализации???

2023-05-15 21:26 UTC, DimaTrushin commented on src/layer.h
> +        ActivationsFunctions::getActivationFunctionByType(functionType);
Перенести в список инициализации.

2023-05-15 21:26 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +  NeuralNetwork(std::vector<LayerDimension>& dimensions,
Плохой конструктор. У тебя LayerDimensions должны быть согласованы. Лучше просто std::initializer_list<size_t> принимать и по ним строить пары.

2023-05-15 21:26 UTC, DimaTrushin commented on src/layer.h
Почему имплементация не вынесена в cpp файл?

2023-05-15 21:26 UTC, DimaTrushin commented on src/layer.h
> +        ActivationsFunctions::getActivationFunctionByType(functionType);
в список инициализации

2023-05-15 21:26 UTC, DimaTrushin commented on src/layer.h
> +  const Layer& operator+=(const LayerDelta& other) & {
Что за странная сигнатура?
```cpp
Layer& operator+=(const LayerDelta& delta) {
  // implementation
}
```
Во-первых, other -- плохое название, потому что это не другой слой, а поправка.
Во-вторых, зачем справа &?
В-третьих, возвращаемый тип некорректен.

2023-05-15 21:26 UTC, DimaTrushin commented on src/lose_functions.h
> +}
Дефолтный case

2023-05-15 21:26 UTC, DimaTrushin commented on examples/mnist/main.cpp
> +const int kImageSize = 28 * 28;
1) constexpr
2) Если тебе нужны глобальные константы, ты можешь завести объект и все константы поместить в него, и у него сделать метод run, который вызывает нужный тест.

2023-05-15 21:26 UTC, DimaTrushin commented on examples/mnist/main.cpp
> +
Когда что-то определяешь в cpp файле, то помещай это в anumynous namespace иначе привет от линкера тебе обеспечен.

2023-05-15 21:26 UTC, DimaTrushin commented on examples/mnist/main.cpp
> +Vector imageToVector(const unsigned char* image_data) {
Ниже ты по сути пишешь mnist parser.

2023-05-15 21:26 UTC, DimaTrushin commented on examples/mnist/main.cpp
> +  dimensions[0] = {predictionSize, imageSize};
То есть у тебя вообще нет внутренних слоев, только входной и выходной и один набор связей?

2023-05-15 21:26 UTC, DimaTrushin commented on examples/mnist/main.cpp
> +                                            LossFunctionType::SQUARE);
1) В начале функции main можно сделать using namespace NeuralNetwork. Это избавить тебя от таких длинных имен. Либо можешь сделать namespace nn = NeuralNetwork.
2) Я бы ожидал такой конструктор
```cpp
auto model = NeuralNetwor({size1, size2, size3}, {Activation::ReLu, Activation::Softmax}, Loss::Square);
```
Надо подумать над сокращением некоторых названий, чтобы enum-ами было проще пользоваться. Так же плохо, что эти enum-ы не enum class-ы. Потому что ты можешь тут пользоваться NeuralNetwork::SQUARE или NeuralNetwork::SOFTMAX, потому что они утекли в окружающий namespace.

2023-05-15 21:26 UTC, DimaTrushin commented on examples/mnist/main.cpp
> +  model.train(10, 2000, images, labels, imagesTest, labelsTest);
- Плохо, что точность нигде не указывается.
- Магические константы.

2023-05-15 21:26 UTC, DimaTrushin commented on examples/mnist/main.cpp
> +int main(int, char*[]) {
Вот я бы переписал эту радость в другом виде. Что-то вроде
1) считать данные
2) обработать данные
3) записать результат
Слишком мелкой возней занимается main.
Если нужны настройки, то создавай функторы, а не функции и пусть они инициализируются дефолтно или в конструкторе.

2023-05-17 18:50 UTC, TorchRik commented on src/layer.h
> +  ssize_t m;
Лучше будут беззнаковые

2023-05-18 07:34 UTC, TorchRik commented on include/NeuralNetwork/neural_network.h
> +      }
Генирируем рандобные индексы сэмплов для тренировки батча

2023-05-18 07:42 UTC, TorchRik commented on include/NeuralNetwork/neural_network.h
> +                    std::vector<size_t>& indexes) {
не-а) исправил

2023-05-18 07:51 UTC, TorchRik commented on include/NeuralNetwork/neural_network.h
> +          LayerDelta{Matrix::Zero(layerDimension.n, layerDimension.m),
Больше ты его не увидишь)

2023-05-18 07:51 UTC, TorchRik commented on include/NeuralNetwork/neural_network.h
> +  void trainByBatch(std::vector<Vector> batchX, std::vector<Vector> batchY,
Да

2023-05-18 07:53 UTC, TorchRik commented on include/NeuralNetwork/neural_network.h
> +  void trainByBatch(std::vector<Vector> batchX, std::vector<Vector> batchY,
Изменил на константную ссылку, действительно лучше сделать приватным

2023-05-18 09:30 UTC, TorchRik commented on include/NeuralNetwork/neural_network.h
> +  [[nodiscard]] std::vector<Vector> computeEachLayer(const Vector& x) const {
Нам же нужны значения на каждом слое для вычисления производных, по этом сохраняю

2023-05-18 09:35 UTC, TorchRik commented on include/NeuralNetwork/neural_network.h
> +    assert(!dimensions.empty());
вынес

2023-05-19 07:38 UTC, TorchRik commented on include/NeuralNetwork/neural_network.h
> +                std::vector<ActivationFunctionType> activationFunctionsTypes,
Ну я же все равно храню слои в векторе, совсем от него избавляться больно

2023-05-19 07:44 UTC, TorchRik commented on include/NeuralNetwork/neural_network.h
> +    size_t layers_size = dimensions.size();
Справился без нее

2023-05-19 07:59 UTC, TorchRik commented on include/NeuralNetwork/neural_network.h
> +          lossFunction_->computeLoss(predict(X[index]), Y[index]) / X.size();
Кажется лучше все же делить в конце

2023-05-19 14:51 UTC, TorchRik commented on include/NeuralNetwork/neural_network.h
> +  void addOnIterationsDeltas(const Vector& x, const Vector& y,
Переименовал

2023-05-20 14:46 UTC, TorchRik commented on include/NeuralNetwork/neural_network.h
> +      }
Вроде нынче этого ифа нет уже

2023-05-20 15:01 UTC, TorchRik commented on include/NeuralNetwork/neural_network.h
> +  NeuralNetwork(const std::string& pathToFile) {
Ну почти успех))
Остались только проблемы с lossfunction и  activationfunction

2023-05-20 15:28 UTC, TorchRik commented on src/layer.h
> +using Vector = Eigen::VectorXd;
Друг за другом не получится в любом случае - т.к на самом низком уровне они в нескольких файлах существует(layer, activationFunction, lossFunction)

2023-05-28 10:30 UTC, TorchRik commented on examples/mnist/main.cpp
> +  dimensions[0] = {predictionSize, imageSize};
Была тестовая версия, итоговая другая

2023-05-28 10:31 UTC, TorchRik commented on examples/mnist/main.cpp
> +Vector imageToVector(const unsigned char* image_data) {
Вынес в отдельный класс и файл

2023-05-28 10:31 UTC, TorchRik commented on examples/mnist/main.cpp
> +
Теперь не актуально

2023-06-05 19:31 UTC, DimaTrushin requested changes
Сделал небольшое количество замечаний по коду.

2023-06-05 19:31 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.cpp
> +    const std::initializer_list<ssize_t>& dimensions,
initializer_list передается by value. Это уже view object.

2023-06-05 19:31 UTC, DimaTrushin commented on examples/mnist/src/mnist_parser.h
> +}  // namespace MNIST
Кирпичи

2023-06-05 19:31 UTC, DimaTrushin commented on examples/mnist/main.cpp
> +double getCountPredicted(const NN::NeuralNetwork& model, std::vector<Vector>& X,
Оберни в anonymous namespace

2023-06-05 19:31 UTC, DimaTrushin commented on examples/mnist/main.cpp
> +  ssize_t iterationCount = 1000;
Сделай графики как падает ошибка от количества итераций.

2023-06-05 19:31 UTC, DimaTrushin commented on examples/mnist/main.cpp
> +  ssize_t batchSize = 2000;
Протестируй зависимость ошибки от размера батча.

2023-06-05 19:31 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.cpp
> +    trainByBatch(X, Y, indexes);
Сделай замер по времени, сколько эта функция работает.
Еще бы хорошо сделать замер без учета времени вывода и подсчета averageLoss. И с подсчетом averageLoss.

2023-06-05 19:31 UTC, DimaTrushin commented on include/NeuralNetwork/neural_network.h
> +using ActivationFunctionType = ActivationsFunctions::ActivationFunctionType;
Это надо перенести внутрь класса NeuralNetwork. Если хочешь объявить глобально, то объяви Vector и Matrix, но в отдельном хедере. А вторые два юзинга уже есть и по хорошему их надо лишь внутри нейросети использовать. Я не люблю глобальные данные, это не локализует зависимости. Лучше в начале каждого класса объявлять все нужные для его работы using-ги, так никогда не запутаешься, что ты использвешь. Так же хорошее правило делать юзинги даже для встроенных типов давая им разумные имена для твоей задачи.

2023-06-05 19:31 UTC, DimaTrushin commented on src/activations_functions.h
> +  Matrix getDerivative(const Vector& x) final {
А почему это не вынесено в cpp файл?

2023-06-05 19:31 UTC, DimaTrushin commented on src/activations_functions.h
> +using Matrix = Eigen::MatrixXd;
Задвоенное объявление вектора и матриц. Сделай эти юзинги тогда отдельным хедером, раз они у тебя глобальные.
Плюс не понятно зачем тебе подnamespace?

2023-06-05 19:31 UTC, DimaTrushin commented on src/activations_functions.h
> +inline std::unique_ptr<BaseActivationFunction> getActivationFunctionByType(
Опять не понятно, почему в header файле.

2023-06-05 19:31 UTC, DimaTrushin commented on src/layer.cpp
> +  os.write(reinterpret_cast<const char*>(&functionType), sizeof(functionType));
Вот для такой работы конечно лучше делать свой класс потоков. Чтобы не тут этим заниматься, а в этом классе. Но это можно сейчас так оставить. В целом рабочий вариант.

2023-06-05 19:31 UTC, DimaTrushin commented on src/lose_functions.h
> +  double computeLoss(const Vector& expected_y,
Почему в хедере?

2023-06-05 19:31 UTC, DimaTrushin commented on src/random.h
> +  void generateIndexes(ssize_t dataSize, ssize_t batchSize,
Почему indices не возвращается через return? Это же rvo в чистом виде и дешево.

2023-06-05 19:31 UTC, DimaTrushin commented on tests/layer_test.cpp
> +TEST(layerTest, randomInit) {
Можешь накидать сюда каких-нибудь еще рандомных тестов для проверки корректности работы всех методов слоя и сети?

2023-06-05 19:31 UTC, DimaTrushin commented on examples/mnist/main.cpp
> +using namespace NN;
Не делай так.

2023-06-05 19:31 UTC, DimaTrushin commented on examples/mnist/src/mnist_parser.h
> +const int kImageSize = 28 * 28;
А эта константа нужна в других файлах? Сделай constexpr или inline. Лучше первое. Иначе это ODR violation.

2023-06-05 20:01 UTC, TorchRik commented on src/random.h
> +  void generateIndexes(ssize_t dataSize, ssize_t batchSize,
Ну казалось бы в такой реализации мы переиспользуем один и тот же вектор при тренировки, кажется дешевле, чем иницилизировать новый вектор каждый раз

2023-06-05 21:10 UTC, merged